default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sequra_development
  username: postgres
  password: postgres
  host: 0.0.0.0
  port: 5432

test:
  <<: *default
  database: sequra_test
  username: postgres
  password: postgres
  host: 0.0.0.0
  port: 5432

production:
  <<: *default
  database: sequra_production
  username: sequra
  password: <%= ENV["SEQURA_DATABASE_PASSWORD"] %>
